export const browserCoreExamples = [
  "qcortex browser status",
  "qcortex browser start",
  "qcortex browser stop",
  "qcortex browser tabs",
  "qcortex browser open https://example.com",
  "qcortex browser focus abcd1234",
  "qcortex browser close abcd1234",
  "qcortex browser screenshot",
  "qcortex browser screenshot --full-page",
  "qcortex browser screenshot --ref 12",
  "qcortex browser snapshot",
  "qcortex browser snapshot --format aria --limit 200",
  "qcortex browser snapshot --efficient",
  "qcortex browser snapshot --labels",
];

export const browserActionExamples = [
  "qcortex browser navigate https://example.com",
  "qcortex browser resize 1280 720",
  "qcortex browser click 12 --double",
  'qcortex browser type 23 "hello" --submit',
  "qcortex browser press Enter",
  "qcortex browser hover 44",
  "qcortex browser drag 10 11",
  "qcortex browser select 9 OptionA OptionB",
  "qcortex browser upload /tmp/qcortex/uploads/file.pdf",
  'qcortex browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "qcortex browser dialog --accept",
  'qcortex browser wait --text "Done"',
  "qcortex browser evaluate --fn '(el) => el.textContent' --ref 7",
  "qcortex browser console --level error",
  "qcortex browser pdf",
];
